### ISSUE TITLE
Todo RQ

### ISSUE THREAD

**Issue by AlbertoSinigaglia** [everbuilds/Docs#55]
cose ancora da fare per RQ:

- [x] (Alberto) Test di accettazione 
- [x] (Alberto) PdQ per metriche e verifiche
- [x] (Giovanni) PdP da controllare incrementi e consuntivo di periodo
- [x] (Alice) Norme da rileggere, 
- [x] (Vittorio, Marco, Alice) create man. manutentore 
- [x] (Riccardo, Giovanni) dettaglio tecnologie mettere breve doc su API, struttura finale progetto (yaml, swagger)

Da fare dopo punti del codice
- [ ] Norme da aggiungere le regole di analisi statica (checkstyle)
- [x] immagini per man. utente

Potenzialmente:

- [ ] aumentare checklist di verifica 
- [x] aumentare il glossario
